name: asr-benchmark-pipe
channels:
  - conda-forge
  - nodefaults
dependencies:
  # core interpreter
  - python==3.12
  - pip
  - python-dotenv
  - ipykernel

  # Base audio and math librairies
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - joblib
  - py-xgboost
  - librosa
  - ffmpeg
  - jupyter
  - jupyterlab

  # Machine Learning and Apple Silicon Specificsy
  - pip:
      - mlx
      - mlx-whisper
      - torch
      - torchaudio
      - torchcodec
      - transformers
      - datasets
      - jiwer
      - gradio